version: "3.7"
services:
  app:
    container_name: petshop-front
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./front:/app
    environment:
      NODE_ENV: development
    networks:
      - petshop-network

networks:
  petshop-network:
    driver: bridge